[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

# Send Ctrl + x + | to tmux (xxd -ps)
[[keyboard.bindings]]
chars = "\u0018|"
key = "H"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control"

[[keyboard.bindings]]
action = "ClearHistory"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "SearchForward"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
action = "SearchBackward"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"