[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

# Send Ctrl + x + | to tmux (use xxd -ps and ctrl+{letter})
[[keyboard.bindings]]
chars = "\u0018|"
key = "|"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0018-"
key = "_"
mods = "Control|Shift"

# Create new tmux pane (new tab)
[[keyboard.bindings]]
chars = "\u0018t"
key = "T"
mods = "Control"

# Switch to next pane
[[keyboard.bindings]]
chars = "\u0018n"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control"

#[[keyboard.bindings]]
#action = "SearchBackward"
#key = "F"
#mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Alt"
