# Change the bind key to Ctl+x
set -g prefix C-x
unbind C-b
bind C-x send-prefix

# Configure pane splitting
unbind % # Split vertically
unbind '"' # Split horizontally
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Create new Tab with Ctl+t
unbind t
bind t new-window -c "#{pane_current_path}"

# Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded config"

# Status Bar config
set -g status on
set -g status-interval 1
set -g automatic-rename on
set -g status-position bottom

set -g window-status-format "#[fg=white]#I:#[fg=blue]#W#[fg=white]"
set -g window-status-current-format "#[bg=default,fg=green]#[bg=green,fg=black,bold] #I:#W#[bg=default,fg=green]"

set -g status-left "#[fg=magenta,bold]  #S"
set -g status-right '#[fg=blue]󱑒 #(date -u +"%%H:%%M %%Z")'

set -g status-justify centre
set -g status-left-length 200   # default: 10
set -g status-right-length 200  # default: 10

set -g status-style bg=default,fg=default
#set -g message-command-style bg=default,fg=green
set -g message-style bg=default,fg=blue
#set -g mode-style bg=${selection_bg},fg=${selection_fg}
set -g pane-active-border-style "fg=default,bg=default"
set -g pane-border-style 'fg=brightblack,bg=default'


# Sensible
set -g status-interval 5
set -g display-time 1500

set -g focus-events on
set -g base-index 1                         # start windows numbering at 1
set -g renumber-windows on
set -g display-panes-time 800               # slightly longer pane indicators display time
set -g default-shell /bin/zsh  
set -g default-terminal "xterm-256color"
set -g mouse on          
set -g set-clipboard on                     # use system clipboard                   # Mouse mode on
set-option -g automatic-rename on
set-window-option -g pane-base-index 1      # make pane numbering consistent with windows


# Plugins
#set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.config/tmux/tpm-plugins"
#set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'erikw/tmux-powerline'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
#run -b '~/.config/tmux/plugins/tpm/tpm'
